services:
  frontend:
    build:
      context: .
      target: development
    container_name: momentum-rider-frontend-dev
    ports:
      - "3000:5173"
    depends_on:
      - backend
    networks:
      - momentum-network
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    labels:
      - "description=Momentum Rider Frontend Development"
      - "version=1.0.0"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./server
      target: development
    container_name: momentum-rider-backend-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - momentum-network
    volumes:
      - ./server:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    labels:
      - "description=Momentum Rider Backend API Development"
      - "version=1.0.0"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  momentum-network:
    driver: bridge
    name: momentum-rider-network